### ISSUE TITLE
What is image mask?

### ISSUE THREAD

**Issue by vvjn** [DeepLearnXMU/DCCN#1]
Hi,
Can you tell me what the image mask (from `path_to_train_img_mask` and `path_to_valid_img_mask` below) is and what it is used for?
Thanks.

```
python train_mmod.py \
 -data demo \
 -save_model demo_modelname \
 -path_to_train_img_feats train-resnet50-res4frelu.npy \
 -path_to_valid_img_feats val-resnet50-res4frelu.npy \
 -path_to_train_attr train_obj.npy \
 -path_to_valid_attr val_obj.npy \
 -path_to_train_img_mask train_obj_mask.npy \
 -path_to_valid_img_mask val_obj_mask.npy \
 -encoder_type transformer -decoder_type transformer --multimodal_model_type dcap
```

**Comment by ShaoDonCui** [comment]
I ran the preprocess.py but got this error, why?
(base) C:\Users\cui\Desktop\my like code\DCCN-master>python preprocess.py -train_src train.lc.norm.tok.en -train_tgt train.lc.norm.tok.de -valid_src val.lc.norm.tok.en -valid_tgt val.lc.norm.tok.de -save_data demo
Extracting features...
 * number of source features: 0.
 * number of target features: 0.
Building `Fields` object...
Building & saving training data...
Traceback (most recent call last):
  File "C:\Users\cui\Desktop\my like code\DCCN-master\onmt\io\TextDataset.py", line 369, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cui\Desktop\my like code\DCCN-master\preprocess.py", line 209, in <module>
    main()
  File "C:\Users\cui\Desktop\my like code\DCCN-master\preprocess.py", line 194, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "C:\Users\cui\Desktop\my like code\DCCN-master\preprocess.py", line 128, in build_save_dataset
    return build_save_text_dataset_in_shards(
  File "C:\Users\cui\Desktop\my like code\DCCN-master\preprocess.py", line 96, in build_save_text_dataset_in_shards
    dataset = onmt.io.TextDataset(
  File "C:\Users\cui\Desktop\my like code\DCCN-master\onmt\io\TextDataset.py", line 76, in __init__
    for ex_values in example_values:
  File "C:\Users\cui\Desktop\my like code\DCCN-master\onmt\io\TextDataset.py", line 68, in <genexpr>
    example_values = ([ex[k] for k in keys] for ex in examples_iter)
  File "C:\Users\cui\Desktop\my like code\DCCN-master\onmt\io\TextDataset.py", line 55, in <genexpr>
    examples_iter = (self._join_dicts(src, tgt) for src, tgt in zip(src_examples_iter, tgt_examples_iter))
RuntimeError: generator raised StopIteration

**Comment by ShaoDonCui** [comment]
can you help me? thank you.
